source 'https://rubygems.org'

gem 'howitzer', github: 'strongqa/howitzer', branch: 'v2.0'

gem 'bundler'
gem 'ffi'
gem 'capybara'
gem 'rest-client'
gem 'repeater'
gem 'her'
gem 'factory_girl'
gem 'syntax'
gem 'cucumber'
gem 'faker'
gem 'nokogiri', '>=1.6.8.rc3'